data:
  snowflake:
    schema: "ml"
    table: "online_shoppers_intention"
  
  features:
    numeric:
      - "ADMINISTRATIVE"
      - "ADMINISTRATIVE_DURATION"
      - "INFORMATIONAL"
      - "INFORMATIONAL_DURATION"
      - "PRODUCTRELATED"
      - "PRODUCTRELATED_DURATION"
      - "BOUNCERATES"
      - "EXITRATES"
      - "PAGEVALUES"
      - "SPECIALDAY"
    categorical:
      - "MONTH"
      - "BROWSER"
      - "REGION"
      - "TRAFFICTYPE"
      - "VISITORTYPE"
      - "WEEKEND"
    target: "REVENUE"
  
  split:
    test_size: 0.2
    random_state: 0

model:
  random_forest:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2
    min_samples_leaf: 1
    random_state: 0
  
  cv:
    n_splits: 5