data:
  snowflake:
    database_prod: "practice"
    database_dev: "practice_dev"
    schema: "ml"
    dataset_table: "dataset"
    source_table: "online_shoppers_intention"

  # 目的変数
  target:
    - "REVENUE"
  
  # 説明変数
  features:
    numeric:
      - "ADMINISTRATIVE"
      - "ADMINISTRATIVE_DURATION"
      - "INFORMATIONAL"
      - "INFORMATIONAL_DURATION"
      - "PRODUCTRELATED"
      - "PRODUCTRELATED_DURATION"
      - "BOUNCERATES"
      - "EXITRATES"
      - "PAGEVALUES"
      - "SPECIALDAY"
      
    categorical:
      - "BROWSER"
      - "REGION"
      - "TRAFFICTYPE"
      - "VISITORTYPE"
      - "WEEKEND"
  
  # 実行日から何ヶ月前までをTraining期間とするか
  period:
    months: 3

  # テストデータの分割
  split:
    test_size: 0.2
    random_state: 0

model:
  cv:
    n_splits: 5
  random_forest:
    random_state: 0

    # optuna での探索範囲
    n_estimators_min: 10
    n_estimators_max: 500
    max_depth_min: 2
    max_depth_max: 30
    min_samples_split_min: 2
    min_samples_split_max: 20
    min_samples_leaf_min: 1
    min_samples_leaf_max: 10
    max_features: ["sqrt", "log2"]
    criterion: ["gini", "entropy"]
