data:
  snowflake:
    database_dev: "mlsystem_dev"
    database_prod: "mlsystem_prod"
    schema: "online_shoppers_intention"
    dataset_table: "dataset"
    source_table: "source"

  target:
    - "REVENUE"
  
  features:
    numeric:
      - "ADMINISTRATIVE"
      - "ADMINISTRATIVE_DURATION"
      - "INFORMATIONAL"
      - "INFORMATIONAL_DURATION"
      - "PRODUCTRELATED"
      - "PRODUCTRELATED_DURATION"
      - "BOUNCERATES"
      - "EXITRATES"
      - "PAGEVALUES"
      - "SPECIALDAY"
      
    categorical:
      - "BROWSER"
      - "REGION"
      - "TRAFFICTYPE"
      - "VISITORTYPE"
      - "WEEKEND"
  
  period:
    months: 3

  split:
    test_size: 0.2
    random_state: 0

model:
  cv:
    n_splits: 5
  random_forest:
    random_state: 0

    n_estimators_min: 10
    n_estimators_max: 500
    max_depth_min: 2
    max_depth_max: 30
    min_samples_split_min: 2
    min_samples_split_max: 20
    min_samples_leaf_min: 1
    min_samples_leaf_max: 10
    max_features: ["sqrt", "log2"]
    criterion: ["gini", "entropy"]
